AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Xpert REST API

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20
    Runtime: nodejs22.x
    Architectures:
      - x86_64
    # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    LoggingConfig:
      LogFormat: JSON
    VpcConfig:
      SecurityGroupIds:
        - sg-0ad55c0c07f70b6ce    # Security group id
      SubnetIds:
        - subnet-fedcde88   
        - subnet-61490238
        - subnet-74fb1513  
    Environment:
      Variables:
        #################################################
        # LocalHost
        #################################################
        # DB_HOST: host.docker.internal
        # DB_USER: "root"
        # DB_PASSWORD: "dataflowisgr8"
        # DB_PORT: "3306"
        # DB_NAME: logportal
        # LOG_LEVEL: debug
        #################################################
        # Remote Host
        #################################################
        DB_HOST: dfe-dev.c1y5lk5xufmn.ap-southeast-2.rds.amazonaws.com
        DB_USER: "odyssey"
        DB_PASSWORD: "d4t4fl0wisgr8"
        DB_PORT: "3306"
        DB_NAME: logportal
        LOG_LEVEL: debug 

Resources:
  #################################################
  # API Gateway
  #################################################
  XpertApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: Xpert API
      StageName: dev
    
      Auth:
        Authorizers:  
          CognitoAuthorizer:
            UserPoolArn: arn:aws:cognito-idp:ap-southeast-2:224788441969:userpool/ap-southeast-2_ZUZUbfNba

  #################################################
  # User Functions
  #################################################

  GetUserByEmailFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Metadata:
       BuildMethod: esbuild
    Properties:
      CodeUri: src/
      Handler: handlers/users/getUserByEmail.lambdaHandler
      Events:
        GetUserByEmail:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            RestApiId: !Ref XpertApi
            Path: /users/email/{email}
            Method: get
  
  ListCustomersFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
    Properties:
      CodeUri: src/
      Handler: handlers/customers/listCustomers.lambdaHandler
      Events:
        ListCustomers:
          Type: Api
          Properties:
            RestApiId: !Ref XpertApi
            Path: /customers
            Method: get
            Auth:
              Authorizer: CognitoAuthorizer
  
  ListUsersFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
    Properties:
      CodeUri: src/
      Handler: handlers/users/listUsers.lambdaHandler
      Events:
        ListUsers:
          Type: Api
          Properties:
            RestApiId: !Ref XpertApi
            Path: /users
            Method: get
    
  # ListUsersByCustomerFunction:
  #   Type: AWS::Serverless::Function
  #   Metadata:
  #     BuildMethod: esbuild
  #   Properties:
  #     CodeUri: src/
  #     Handler: handlers/customers/listUsers.lambdaHandler
  #     Events:
  #       ListUsersByCustomer:
  #         Type: Api
  #         Properties:
  #           RestApiId: !Ref XpertApi
  #           Path: /customers/{id}/users
  #           Method: get  
  
  ListGroupsByCustomerUserFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
    Properties:
      CodeUri: src/
      Handler: handlers/customers/listGroupsByCustomerUser.lambdaHandler
      Events:
        ListUsersByCustomer:
          Type: Api
          Properties:
            RestApiId: !Ref XpertApi
            Path: /customers/{cid}/users/{uid}/groups
            Method: get

Outputs:
  ApiUrl:
    Description: API Gateway endpoint
    Value: !Sub "https://${XpertApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
