AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Xpert REST API

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20
    Runtime: nodejs22.x
    Architectures:
      - x86_64
    # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    LoggingConfig:
      LogFormat: JSON
    VpcConfig:
      SecurityGroupIds:
        - sg-0ad55c0c07f70b6ce    # Security group id
      SubnetIds:
        - subnet-fedcde88   
        - subnet-61490238
        - subnet-74fb1513  
    Environment:
      Variables:
        #################################################
        # LocalHost
        #################################################
        # DB_HOST: host.dnocker.internal
        # DB_USER: "root"
        # DB_PASSWORD: "dataflowisgr8"
        # DB_PORT: "3306"
        # DB_NAME: logportal
        # LOG_LEVEL: debug
        #################################################
        # Dev Remote Host
        #################################################
        DB_HOST: dfe-dev.c1y5lk5xufmn.ap-southeast-2.rds.amazonaws.com
        DB_USER: "odyssey"
        DB_PASSWORD: "d4t4fl0wisgr8"
        DB_PORT: "3306"
        DB_NAME: logportal
        LOG_LEVEL: debug
        DDB_AUDIT_TABLE_NAME: odyAuditTrail  

Resources:
  #################################################
  # API Gateway
  #################################################
  XpertApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: Xpert API
      StageName: dev
    
      Auth:
        Authorizers:  
          CognitoAuthorizer:
            UserPoolArn: arn:aws:cognito-idp:ap-southeast-2:224788441969:userpool/ap-southeast-2_ZUZUbfNba

      Cors:
        AllowMethods: "'GET,POST,PUT,PATCH,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,Authorization'"
        AllowOrigin: "'http://localhost:3000'"

  AuditDynamoDBWritePolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - dynamodb:PutItem
            Resource:
              - arn:aws:dynamodb:ap-southeast-2:224788441969:table/odyAuditTrail
              
  #################################################
  # User Functions
  #################################################

  GetUserByEmailFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Metadata:
       BuildMethod: esbuild
    Properties:
      CodeUri: src/
      Handler: handlers/users/getUserByEmail.lambdaHandler
      Events:
        GetUserByEmail:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            RestApiId: !Ref XpertApi
            Path: /users/email/{email}
            Method: get
            Auth:
              Authorizer: CognitoAuthorizer
  
  ListCustomersFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
    Properties:
      CodeUri: src/
      Handler: handlers/customers/listCustomers.lambdaHandler
      Events:
        ListCustomers:
          Type: Api
          Properties:
            RestApiId: !Ref XpertApi
            Path: /customers
            Method: get
            Auth:
              Authorizer: CognitoAuthorizer
  
  ListUsersFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
    Properties:
      CodeUri: src/
      Handler: handlers/users/listUsers.lambdaHandler
      Events:
        ListUsers:
          Type: Api
          Properties:
            RestApiId: !Ref XpertApi
            Path: /users
            Method: get
    
  ListUsersByCustomerFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
    Properties:
      CodeUri: src/
      Handler: handlers/customers/listUsersByCustomer.lambdaHandler
      Events:
        ListUsersByCustomer:
          Type: Api
          Properties:
            RestApiId: !Ref XpertApi
            Path: /customers/{cid}/users
            Method: get
            Auth:
              Authorizer: CognitoAuthorizer  
  
  ListGroupsByCustomerUserFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
    Properties:
      CodeUri: src/
      Handler: handlers/customers/listGroupsByCustomerUser.lambdaHandler
      Events:
        ListGroupsByCustomer:
          Type: Api
          Properties:
            RestApiId: !Ref XpertApi
            Path: /customers/{cid}/users/{uid}/groups
            Method: get
            Auth:
              Authorizer: CognitoAuthorizer
  
  ListLoggersByCustomerUserGroupFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
    Properties:
      CodeUri: src/
      Handler: handlers/customers/listLoggersByCustomerUserGroup.lambdaHandler
      Events:
        ListLoggersByCustomerUser:
          Type: Api
          Properties:
            RestApiId: !Ref XpertApi
            Path: /customers/{cid}/users/{uid}/group/{gid}/loggers
            Method: get
            Auth:
              Authorizer: CognitoAuthorizer
    
  UpdateLoggerConfigSettingsFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
    Properties:
      CodeUri: src/
      Handler: handlers/loggers/updateLoggerConfigSettings.lambdaHandler
      Policies:
        - !Ref AuditDynamoDBWritePolicy
      Events:
        UpdateLoggerConfigSettings:
          Type: Api
          Properties:
            RestApiId: !Ref XpertApi
            Path: /loggers/config
            Method: patch
            Auth:
              Authorizer: CognitoAuthorizer
  
  fetchLoggerConfigSettingsFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
    Properties:
      CodeUri: src/
      Handler: handlers/loggers/fetchLoggerConfigSettings.lambdaHandler
      Events:
        fetchLoggerConfigSettings:
          Type: Api
          Properties:
            RestApiId: !Ref XpertApi
            Path: /loggers/{lid}/config
            Method: get
            Auth:
              Authorizer: CognitoAuthorizer

Outputs:
  ApiUrl:
    Description: API Gateway endpoint
    Value: !Sub "https://${XpertApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
